package frc.robot.subsystems.turret;

import java.util.function.DoubleSupplier;

import org.prime.subsystems.LoggedSubsystem;
import org.prime.util.MutVector;
import org.prime.util.PhysicsConstants;

import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.controls.VelocityVoltage;

import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.FieldTargets;
import frc.robot.Robot;
import frc.robot.SuperStructure;

import static org.prime.util.PhysicsConstants.GRAVITY;

public class Turret extends LoggedSubsystem {
    private ITurret _turret;

    public enum FlywheelState {
        IDLE,
        SHOOTING,
        STOPPED
    }

    public enum TargetingState {
        MANUAL,
        AUTO,
        STOPPED
    }

    public enum LockOnState {
        SHOT_CALCULATED,
        SHOT_NOT_CALCULATED,
        YAW_LOCKED_ON,
        YAW_NOT_LOCKED_ON,
        FLYWHEEL_AT_SPEED,
        FLYWHEEL_NOT_AT_SPEED
    }

    public enum UptakeState {
        FORWARDS,
        REVERSED,
        STOPPED
    }

    // CTRE Control Requests
    private final VelocityVoltage _flywheelControl = new VelocityVoltage(0);
    private final MotionMagicVoltage _yawControl = new MotionMagicVoltage(0);
    private final DutyCycleOut _yawManualControl = new DutyCycleOut(0);
    private double _manualFlywheelVelocityRPS;
    private double _manualYawInput;

    // Mutable Vectors
    private final MutVector _mutNominalTargetVector = new MutVector();
    private final MutVector _mutRobotVelocityVector = new MutVector();
    private final MutVector _mutTurretTangentVelocityVector = new MutVector();

    // Manual Control Suppliers
    private DoubleSupplier _yawSupplier;
    private DoubleSupplier _pitchSupplier;

    public Turret() {
        setName("Turret");
        _turret = Robot.isReal()
                ? new TurretReal()
                : new TurretSim();
    }

    /**
     * Sets the vector to shoot from a source pose to a target pose
     * @param sourcePose The source pose
     * @param targetPose The target pose
     * @param minAngle The minimum angle of the projectile
     * @param maxAngle The maximum angle of the projectile
     * @param minSpeed The minimum speed of the projectile
     * @param maxSpeed The maximum speed of the projectile
     * @throws Exception If no valid shot solution is found
     */
    public void calculateAimVector(MutVector target, Pose3d sourcePose, Pose3d targetPose,
            double minAngle, double maxAngle, double minSpeed, double maxSpeed) throws Exception {

        // this code is largely generated by claude
        // somewhat reviewed by me but
        // TODO: double check and improve

        // calculate angle and distance (x, y)
        double deltaX = targetPose.getX() - sourcePose.getX();
        double deltaY = targetPose.getY() - sourcePose.getY();
        double yaw = Math.toDegrees(Math.atan2(deltaY, deltaX));
        double distance = Math.hypot(deltaX, deltaY);

        // calculate height difference (z)
        double shooterHeight = TurretMap.TURRET_HEIGHT_ABOVE_GROUND;
        double targetHeight = targetPose.getZ() + TurretMap.HUB_OVERSHOOT_HEIGHT;
        double deltaH = targetHeight - shooterHeight;

        // utilize optimal angle formula (45° + (arctan(deltaH / distance) / 2)
        double optimalFromHorizontal = 45.0 + (Math.toDegrees(Math.atan2(deltaH, distance)) / 2.0);

        // subtract 90 to convert from "from horizontal" to "from vertical" for turret math
        double angle = Math.max(minAngle, Math.min(maxAngle, 90 - optimalFromHorizontal));

        // convert back to "from horizontal" for physics math by subtracting from 90
        double physicsAngleRad = Math.toRadians(90.0 - angle);
        double cos = Math.cos(physicsAngleRad);
        double tan = Math.tan(physicsAngleRad);

        // calculate initial exit speed
        double denominator = 2 * cos * cos * (distance * tan - deltaH);

        if (denominator <= 0) {
            throw new Exception("geometry impossible at optimal angle");
        }

        double vSquared = PhysicsConstants.GRAVITY * distance * distance / denominator;

        if (vSquared <= 0) {
            throw new Exception("negative vSquared");
        }

        double v = Math.sqrt(vSquared);

        // validate against limits
        if (v < minSpeed || v > maxSpeed) {
            throw new Exception(String.format(
                    "required speed %.2f m/s outside [%.2f, %.2f]",
                    v, minSpeed, maxSpeed));
        }

        _mutNominalTargetVector.setPolar(v, angle, yaw);
    }

    public MutVector calculateTurretVectorFromRobotPose(Pose3d targetPose) {
        var robotPose = new Pose3d(SuperStructure.Swerve.EstimatedRobotPose);

        var targetDistance = targetPose.getTranslation().getDistance(robotPose.getTranslation());
        if (targetDistance < TurretMap.MIN_SHOT_DISTANCE_METERS) {
            SuperStructure.Turret.ShotCalculationState = LockOnState.SHOT_NOT_CALCULATED;
            return _mutNominalTargetVector;
        }

        try {
            calculateAimVector(
                    _mutNominalTargetVector,
                    robotPose,
                    targetPose,
                    TurretMap.HOOD_MIN_ANGLE_DEGREES,
                    TurretMap.HOOD_MAX_ANGLE_DEGREES,
                    TurretMap.FLYWHEEL_MIN_SPEED,
                    TurretMap.FLYWHEEL_MAX_SPEED);
            SuperStructure.Turret.ShotCalculationState = LockOnState.SHOT_CALCULATED;

            // TODO: Enable after empirical measurements correlating distance to required flywheel speed are taken
            if (TurretMap.USE_SPEED_INTERPOLATION) {
                var interpolatedFlywheelSpeed = TurretMap.DISTANCE_TO_FLYWHEEL_SPEED_MAP.get(targetDistance);
                _mutNominalTargetVector.setMagnitude(interpolatedFlywheelSpeed);
            }

            // TODO: Refine motion compensation, enable, and test
            if (TurretMap.AUTO_MOTION_COMPENSATION) {
                var shotTimeToTarget = _mutNominalTargetVector.getTimeToTarget(targetDistance);
                ChassisSpeeds chassisSpeeds = SuperStructure.Swerve.RobotRelativeChassisSpeeds;

                _mutRobotVelocityVector.setCartesian(
                        chassisSpeeds.vxMetersPerSecond,
                        chassisSpeeds.vyMetersPerSecond,
                        0);

                _mutTurretTangentVelocityVector.setPolar(
                        chassisSpeeds.omegaRadiansPerSecond * TurretMap.TURRET_DISTANCE_FROM_ROBOT_CENTER,
                        0,
                        TurretMap.TURRET_ROTATION_FROM_ROBOT_CENTER_TANGENT.getDegrees());

                return _mutNominalTargetVector
                        .minus(_mutRobotVelocityVector.plus(_mutTurretTangentVelocityVector));
            } else {
                return _mutNominalTargetVector;
            }
        } catch (Exception e) {
            SuperStructure.Turret.ShotCalculationState = LockOnState.SHOT_NOT_CALCULATED;
            return _mutNominalTargetVector;
        }
    }

    public void setYawSupplier(DoubleSupplier supplier) {
        _yawSupplier = supplier;
    }

    public void setPitchSupplier(DoubleSupplier supplier) {
        _pitchSupplier = supplier;
    }

    private void actOnState(TurretInputsAutoLogged inputs) {
        MutVector aimVector = null;

        if (inputs.TargetingState == TargetingState.AUTO) {
            var target = resolveAutoTarget();

            aimVector = calculateTurretVectorFromRobotPose(target);
            logTrajectory(target, aimVector);
        }

        actOnTargetingState(inputs.TargetingState, aimVector);
        actOnFlywheelState(inputs.FlywheelState, inputs.TargetingState, aimVector);
        actOnFeedState(inputs.FeedState);
    }

    /**
     * Resolves the target position for auto-aiming.
     * Uses the passing position if the robot is in the neutral zone, otherwise targets the hub.
     */
    private Pose3d resolveAutoTarget() {
        var target = FieldTargets.GetPassingPosition(SuperStructure.Swerve.EstimatedRobotPose);
        if (target == null) {
            // We are not in the neutral zone, target the hub.
            target = FieldTargets.GetHubPosition();
        }

        double velocityX = _mutNominalTargetVector.getX();
        double velocityY = _mutNominalTargetVector.getY();
        double velocityZ = _mutNominalTargetVector.getZ();

        double initialX = SuperStructure.Swerve.EstimatedRobotPose.getX();
        double initialY = SuperStructure.Swerve.EstimatedRobotPose.getY();
        double initialZ = TurretMap.TURRET_HEIGHT_ABOVE_GROUND;

        var deltaX = target.getX() - SuperStructure.Swerve.EstimatedRobotPose.getX();
        var deltaY = target.getY() - SuperStructure.Swerve.EstimatedRobotPose.getY();
        var distance = Math.hypot(deltaX, deltaY);

        //            var totalTime = 0.0;
        //
        //            if (_mutNominalTargetVector.getTimeToTarget(distance).in(Units.Seconds) != -1) {
        //                totalTime = _mutNominalTargetVector.getTimeToTarget(distance).in(Units.Seconds);
        //            }

        var totalTime = 10;

        var timeStep = 0.05;

        int numPoints = (int) (totalTime / timeStep) + 1;
        Pose3d[] trajectory = new Pose3d[numPoints];

        for (int i = 0; i < numPoints; i++) {
            double t = i * timeStep;

            // Projectile motion equations
            double x = initialX + velocityX * t;
            double y = initialY + velocityY * t;
            double z = initialZ + velocityZ * t - 0.5 * GRAVITY * t * t;

            // Calculate velocity direction for orientation
            double vx = velocityX;
            double vy = velocityY;
            double vz = velocityZ - GRAVITY * t;

            // Create rotation based on velocity direction
            double pitch = Math.atan2(vz, Math.sqrt(vx * vx + vy * vy));
            double yaw = Math.atan2(vy, vx);

            trajectory[i] = new Pose3d(
                    new Translation3d(x, y, z),
                    new Rotation3d(0, pitch, yaw));
        }

        recordOutput("Optimal Fuel Trajectory", trajectory);
        recordOutput("Target Pose", target);
        return target;
    }

    /**
     * Computes and logs the predicted projectile trajectory for visualization.
     */
    private void logTrajectory(Pose3d target, MutVector aimVector) {
        double velocityX = _mutNominalTargetVector.getX();
        double velocityY = _mutNominalTargetVector.getY();
        double velocityZ = _mutNominalTargetVector.getZ();

        double initialX = SuperStructure.Swerve.EstimatedRobotPose.getX();
        double initialY = SuperStructure.Swerve.EstimatedRobotPose.getY();
        double initialZ = TurretMap.TURRET_HEIGHT_ABOVE_GROUND;

        // TODO: Replace hardcoded totalTime with calculated time-to-target once validated
        // var totalTime = _mutNominalTargetVector.getTimeToTarget(distance).in(Units.Seconds);
        var totalTime = 3;
        var timeStep = 0.05;

        int numPoints = (int) (totalTime / timeStep) + 1;
        Pose3d[] trajectory = new Pose3d[numPoints];

        for (int i = 0; i < numPoints; i++) {
            double t = i * timeStep;

            // Projectile motion equations
            double x = initialX + velocityX * t;
            double y = initialY + velocityY * t;
            double z = initialZ + velocityZ * t - 0.5 * GRAVITY * t * t;

            // Calculate velocity direction for orientation
            double vx = velocityX;
            double vy = velocityY;
            double vz = velocityZ - GRAVITY * t;

            // Create rotation based on velocity direction
            double pitch = Math.atan2(vz, Math.sqrt(vx * vx + vy * vy));
            double yaw = Math.atan2(vy, vx);

            trajectory[i] = new Pose3d(
                    new Translation3d(x, y, z),
                    new Rotation3d(0, pitch, yaw));
        }

        recordOutput("Optimal Fuel Trajectory", trajectory);
        recordOutput("Target Pose", target);
    }

    /**
     * Controls turret yaw and hood based on the current targeting state.
     * 
     * @param targetingState The current targeting mode (MANUAL, AUTO, or STOPPED)
     * @param aimVector The calculated aim vector (only used in AUTO mode, may be null otherwise)
     */
    private void actOnTargetingState(TargetingState targetingState, MutVector aimVector) {
        switch (targetingState) {
            // TODO: Implement pitch control once CAD finalizes turret
            case MANUAL:
                _turret.controlYaw(
                        _yawManualControl.withOutput(TurretMap.YAW_MAX_MANUAL_SPEED * _yawSupplier.getAsDouble()));

                // TODO: Limit hood motion based on current angle and max/min angle
                _turret.controlHood(TurretMap.PITCH_MAX_MANUAL_SPEED * _pitchSupplier.getAsDouble()); // <hood pitch implementation>
                break;
            case AUTO:
                var yaw = aimVector.getYaw();
                yaw += _manualYawInput * TurretMap.AUTO_AIM_YAW_TRIM_DEGREES;
                _turret.controlYaw(_yawControl.withPosition(yaw));

                // var pitch = aimVector.getPitch();
                // <hood pitch implementation>
                break;
            case STOPPED:
            default:
                _turret.controlFlywheel(_flywheelControl.withVelocity(0));
                _turret.controlYaw(_yawManualControl.withOutput(0));
                break;
        }
    }

    /**
     * Controls the flywheel based on the current flywheel state and targeting mode.
     * 
     * @param flywheelState The desired flywheel behavior (IDLE, SHOOTING, or STOPPED)
     * @param targetingState The current targeting mode, used to determine manual vs auto speed
     * @param aimVector The calculated aim vector for deriving auto flywheel speed (may be null)
     */
    private void actOnFlywheelState(FlywheelState flywheelState, TargetingState targetingState, MutVector aimVector) {
        switch (flywheelState) {
            case IDLE:
                _turret.controlFlywheel(_flywheelControl.withVelocity(TurretMap.FLYWHEEL_IDLE_VELOCITY_RPS));
                break;
            case STOPPED:
                _turret.controlFlywheel(_flywheelControl.withVelocity(0));
                break;
            case SHOOTING:
                if (targetingState == TargetingState.MANUAL) {
                    _turret.controlFlywheel(_flywheelControl.withVelocity(_manualFlywheelVelocityRPS));
                } else {
                    // Temp relation between flywheel speed and fuel velocity, will be replaced
                    // with a more concrete relation after testing
                    var targetVelocity = aimVector.getMagnitude();
                    var targetFlywheelOmega = (targetVelocity * (7 / 2)) / TurretMap.FLYWHEEL_RADIUS;
                    _turret.controlFlywheel(_flywheelControl.withVelocity(targetFlywheelOmega));
                }
                break;
        }
    }

    /**
     * Controls the turret feeder based on the current feed state.
     * 
     * @param feedState The desired feeder direction (FORWARDS, REVERSED, or STOPPED)
     */
    private void actOnFeedState(UptakeState feedState) {
        switch (feedState) {
            case FORWARDS:
                _turret.setFeederSpeed(.5);
                break;
            case REVERSED:
                _turret.setFeederSpeed(-.5);
                break;
            case STOPPED:
            default:
                _turret.setFeederSpeed(0);
                break;
        }
    }

    /**
     * Calculates the limelight's 3D pose (position and rotation) relative to the robot's centerpoint on the ground.
     * 
     * This method accounts for:
     * - The turret's rotation origin offset from the robot center
     * - The current turret rotation angle
     * - The limelight's fixed offset from the turret rotation center
     * - The limelight's fixed POV angle relative to the turret
     * 
     * @return Pose3d representing the limelight's position (XYZ) and rotation (pitch, yaw, roll) 
     *         from the robot's centerpoint on the ground
     */
    public Pose3d getLimelightPose3dFromRobotCenter() {
        // Get current turret rotation from inputs
        double turretRotationRadians = SuperStructure.Turret.TurretRotation.getRadians();

        // Step 1: Calculate turret rotation center position from robot center
        Translation3d turretCenterFromRobotCenter = new Translation3d(
                TurretMap.TURRET_CENTER_OFFSET_X,
                TurretMap.TURRET_CENTER_OFFSET_Y,
                TurretMap.TURRET_CENTER_OFFSET_Z);

        // Step 2: Calculate limelight offset from turret center, accounting for turret rotation
        // The limelight offset rotates with the turret around the Z-axis (yaw)
        double rotatedLimelightX = TurretMap.LIMELIGHT_OFFSET_X * Math.cos(turretRotationRadians)
                - TurretMap.LIMELIGHT_OFFSET_Y * Math.sin(turretRotationRadians);
        double rotatedLimelightY = TurretMap.LIMELIGHT_OFFSET_X * Math.sin(turretRotationRadians)
                + TurretMap.LIMELIGHT_OFFSET_Y * Math.cos(turretRotationRadians);

        Translation3d limelightOffsetFromTurretCenter = new Translation3d(
                rotatedLimelightX,
                rotatedLimelightY,
                TurretMap.LIMELIGHT_OFFSET_Z // Z offset doesn't change with rotation
        );

        // Step 3: Combine to get total limelight position from robot center
        Translation3d limelightPositionFromRobotCenter = turretCenterFromRobotCenter
                .plus(limelightOffsetFromTurretCenter);

        // Step 4: Calculate limelight rotation
        // The limelight's rotation includes both its fixed POV angle and the turret's rotation
        Rotation3d limelightRotation = new Rotation3d(
                TurretMap.LIMELIGHT_ROLL, // Roll (around X-axis)
                TurretMap.LIMELIGHT_PITCH, // Pitch (around Y-axis)
                TurretMap.LIMELIGHT_YAW + turretRotationRadians // Yaw (around Z-axis) - includes turret rotation
        );

        // Step 5: Create and return the final Pose3d
        return new Pose3d(limelightPositionFromRobotCenter, limelightRotation);
    }

    @Override
    public void periodic() {
        _turret.updateInputs(SuperStructure.Turret);
        SuperStructure.Turret.LimelightPoseFromRobotCenter = getLimelightPose3dFromRobotCenter();
        // TODO: Currently in field relative, possibly change later

        processInputs(SuperStructure.Turret);

        actOnState(SuperStructure.Turret);

        SuperStructure.Turret.targetVector = _mutNominalTargetVector.getTranslation3d()
                .plus(new Translation3d(SuperStructure.Swerve.EstimatedRobotPose.getTranslation()));
    }

    public Command setFlywheel(FlywheelState state) {
        return this.runOnce(() -> SuperStructure.Turret.FlywheelState = state);
    }

    public Command setFlywheelManualSpeedRps(double rps) {
        return this.runOnce(() -> _manualFlywheelVelocityRPS = rps);
    }

    public Command setTargeting(TargetingState state) {
        return this.runOnce(() -> SuperStructure.Turret.TargetingState = state);
    }

    /**
     * Sets the manual yaw input for turret control. This input is used as a trim multiplier in AUTO targeting mode and as direct control input in MANUAL targeting mode.
     * @param input
     * @return
     */
    public Command setTargetingManualYawInput(double input) {
        return this.runOnce(() -> _manualYawInput = input);
    }

    public Command setFeed(UptakeState state) {
        return this.runOnce(() -> SuperStructure.Turret.FeedState = state);
    }
}
